// Auto-generated by scripts/gen_action_cards.py - DO NOT EDIT.
#pragma once

#include <lvgl.h>
#include <array>
#include <string_view>

// Flipped to 1 only when every act_<slug>.ogg voice clip exists,
// so the firmware always builds even before audio is generated.
#define ACTION_CARDS_HAVE_AUDIO 1

#if ACTION_CARDS_HAVE_AUDIO
#include "assets/lang_config.h"
#endif

extern const lv_image_dsc_t get_up;
extern const lv_image_dsc_t go_toilet;
extern const lv_image_dsc_t brush_teeth;
extern const lv_image_dsc_t wash_face;
extern const lv_image_dsc_t comb_hair;
extern const lv_image_dsc_t wear_clothes;
extern const lv_image_dsc_t wear_shoes;
extern const lv_image_dsc_t wash_hands;
extern const lv_image_dsc_t take_bath;
extern const lv_image_dsc_t action_card_sleep;

struct ActionCard {
    const lv_image_dsc_t* image;  // 240x240 RGB565 picture
    const char* name;             // Chinese name, no extension
#if ACTION_CARDS_HAVE_AUDIO
    std::string_view sound;       // offline Ogg: 妈妈，我要 + name
#endif
};

static const std::array<ActionCard, 10> kActionCards = {{
    { &get_up, "起床", Lang::Sounds::OGG_ACT_GET_UP },
    { &go_toilet, "上洗手间", Lang::Sounds::OGG_ACT_GO_TOILET },
    { &brush_teeth, "刷牙", Lang::Sounds::OGG_ACT_BRUSH_TEETH },
    { &wash_face, "洗脸", Lang::Sounds::OGG_ACT_WASH_FACE },
    { &comb_hair, "梳头", Lang::Sounds::OGG_ACT_COMB_HAIR },
    { &wear_clothes, "穿衣服", Lang::Sounds::OGG_ACT_WEAR_CLOTHES },
    { &wear_shoes, "穿鞋子", Lang::Sounds::OGG_ACT_WEAR_SHOES },
    { &wash_hands, "洗手", Lang::Sounds::OGG_ACT_WASH_HANDS },
    { &take_bath, "洗澡", Lang::Sounds::OGG_ACT_TAKE_BATH },
    { &action_card_sleep, "睡觉", Lang::Sounds::OGG_ACT_SLEEP },
}};
