// Auto-generated by scripts/gen_action_cards.py - DO NOT EDIT.
#pragma once

#include <lvgl.h>

extern const lv_image_dsc_t welcome_ni;
extern const lv_image_dsc_t please_choose;
extern const lv_image_dsc_t what_you_want;
extern const lv_image_dsc_t celebrate_highfive;
extern const lv_image_dsc_t you_great;
